name: CI with Gradle - Automated Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mesmorize
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2


      - name: Make the application.properties from application.properties.example
        run: cp backend/src/main/resources/application.properties.example backend/src/main/resources/application.properties

      - name: Make gradlew executable
        run: chmod +x ./backend/gradlew

      - name: Execute Gradle test
        run: ./backend/gradlew test

      - name: Execute Gradle build
        run: ./backend/gradlew build

